force-app/main/default/objects/Test_Run__c/Test_Run__c.object-meta.xml
<CustomObject>
    <label>Test Run</label>
    <nameField>
        <label>Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run__c/fields/Parent_Job_Ids__c.field-meta.xml
<CustomField>
    <fullName>Parent_Job_Ids__c</fullName>
    <externalId>true</externalId>
    <label>Parent Job Ids</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when the test run has completed and has been processed by the TestRunner package.</description>
    <inlineHelpText>True when the test run has completed and has been processed by the TestRunner package.</inlineHelpText>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/Test_Run_Method_Result__c.object-meta.xml
<CustomObject>
    <label>Test Run Method Result</label>
    <nameField>
        <label>Apex Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Run Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Failure_Audit__c.field-meta.xml
<CustomField>
    <fullName>Failure_Audit__c</fullName>
    <formula>IF(Method_Pass__c == false,
&quot;SELECT Id, Action, CreatedBy.Name, CreatedDate, Display, Section FROM SetupAuditTrail WHERE CreatedDate &gt; &quot; &amp; SUBSTITUTE(TEXT(Last_Success__c), &apos; &apos;, &apos;T&apos;) &amp; &quot; AND CreatedDate &lt; &quot; &amp; SUBSTITUTE(TEXT(First_Failure__c), &apos; &apos;, &apos;T&apos;),
&quot;Method Passed&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Failure Audit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/First_Failure__c.field-meta.xml
<CustomField>
    <fullName>First_Failure__c</fullName>
    <description>DateTime of first failed attempt at test</description>
    <label>First Failure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Last_Success__c.field-meta.xml
<CustomField>
    <fullName>Last_Success__c</fullName>
    <description>DateTime of last successful run of test</description>
    <label>Last Success</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Method_Pass__c.field-meta.xml
<CustomField>
    <fullName>Method_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Method Pass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Test_Run__c</fullName>
    <label>Test Run</label>
    <referenceTo>Test_Run__c</referenceTo>
    <relationshipLabel>Test Run Method Results</relationshipLabel>
    <relationshipName>Test_Run_Method_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestRunProcessorTest.cls
/**
 * Unit tests for Run Processor
 */
@isTest
private class TestRunProcessorTest {
    @isTest
    public static void testQueuer() {
        TestRunProcessor testProcessor = new TestRunProcessor();
        testProcessor.testResults = generateTestResults();

        Test.StartTest();
        System.schedule('Automated Test Job Queuer [UNIT TESTING]', '0 0 23 * * ?', testProcessor);
        testProcessor.execute(null);
        List<Test_Run_Method_Result__c> processorResults = [
            SELECT Method_Name__c, Method_Pass__c
            FROM Test_Run_Method_Result__c
            WHERE Name = 'Generic'
        ];
        System.assertEquals('Test1', processorResults[0].Method_Name__c);
        System.assertEquals(true, processorResults[0].Method_Pass__c);

        Test.stopTest();
    }

    @isTest
    public static void PassFailProcessorTest() {
        generateTestRunResults();
        //wait a second
        Integer start = System.Now().second();
        while (System.Now().second() < start + 1) {
        }
        TestRunProcessor testProcessor = new TestRunProcessor();
        testProcessor.testResults = generateTestResults();

        Test.StartTest();
        testProcessor.execute(null);
        List<Test_Run_Method_Result__c> processorResults = [
            SELECT
                Method_Name__c,
                Method_Pass__c,
                Test_Run__c,
                CreatedDate,
                First_Failure__c,
                Last_Success__c,
                Failure_Audit__c
            FROM Test_Run_Method_Result__c
            WHERE Name = 'PassFailProccess'
            ORDER BY CreatedDate DESC
        ];
        for (Test_Run_Method_Result__c tr : processorResults) {
            System.debug('Test: ' + tr.Method_Name__c);
            System.debug('Pass Fail: ' + tr.Method_Pass__c);
            System.debug('Date: ' + tr.CreatedDate);
            System.debug('Audit: ' + tr.Failure_Audit__c);
        }

        System.assertEquals('Test2', processorResults[0].Method_Name__c);
        System.assertNotEquals(processorResults[0].CreatedDate, processorResults[0].First_Failure__c);
        System.assertEquals('Method Passed', processorResults[2].Failure_Audit__c);

        Test.stopTest();
    }

    private static List<ApexTestResult> generateTestResults() {
        List<ApexClass> classes = [SELECT Id, Name, Body FROM ApexClass WHERE Name = 'TestRunProcessorTest'];

        Test_Run__c testRun = new Test_Run__c(Parent_Job_Ids__c = '7073t00005OHeNPCA1', Processed__c = false);
        insert testRun;
        List<ApexTestResult> testResults = new List<ApexTestResult>{
            new ApexTestResult(
                Outcome = 'Pass',
                MethodName = 'Test1',
                Message = 'asdf',
                StackTrace = 'asdf',
                AsyncApexJobId = testRun.Parent_Job_Ids__c,
                ApexClass = new ApexClass(Name = 'Generic')
            ),
            new ApexTestResult(
                Outcome = 'Fail',
                MethodName = 'Test2',
                Message = 'asdf',
                StackTrace = 'asdf',
                AsyncApexJobId = testRun.Parent_Job_Ids__c,
                ApexClass = new ApexClass(Name = 'PassFailProccess')
            )
        };
        return testResults;
    }
    private static void generateTestRunResults() {
        List<Test_Run__c> testRun = new List<Test_Run__c>{
            new Test_Run__c(Parent_Job_Ids__c = '7073t00005OHeNPAA1', Processed__c = true),
            new Test_Run__c(Parent_Job_Ids__c = '7073t00005OHbgxAAD', Processed__c = true)
        };
        insert testRun;
        List<Test_Run_Method_Result__c> testRunResults = new List<Test_Run_Method_Result__c>{
            new Test_Run_Method_Result__c(
                Message__c = 'asdf',
                Method_Name__c = 'Test2',
                Method_Pass__c = false,
                Name = 'PassFailProccess',
                Stack_Trace__c = 'asdf',
                Test_Run__c = testRun[0].Id
            ),
            new Test_Run_Method_Result__c(
                Message__c = 'asdf',
                Method_Name__c = 'Test2',
                Method_Pass__c = true,
                Name = 'PassFailProccess',
                Stack_Trace__c = 'asdf',
                Test_Run__c = testRun[1].Id
            )
        };
        insert testRunResults;
    }
}