force-app/main/default/objects/Test_Run__c/Test_Run__c.object-meta.xml
<CustomObject>
    <label>Test Run</label>
    <nameField>
        <label>Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run_Method_Result__c/Test_Run_Method_Result__c.object-meta.xml
<CustomObject>
    <label>Test Run Method Result</label>
    <nameField>
        <label>Apex Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Run Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/First_Failure__c.field-meta.xml
<CustomField>
    <fullName>First_Failure__c</fullName>
    <description>DateTime of first failed attempt at test</description>
    <label>First Failure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Method_Pass__c.field-meta.xml
<CustomField>
    <fullName>Method_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Method Pass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Test_Run__c</fullName>
    <label>Test Run</label>
    <referenceTo>Test_Run__c</referenceTo>
    <relationshipLabel>Test Run Method Results</relationshipLabel>
    <relationshipName>Test_Run_Method_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

notifications/workflow-email/classes/TestRunEmailController.cls
public class TestRunEmailController {
    List<Test_Run_Method_Result__c> queryResults;
    public Id testRunId { get; set; }
    public String getbaseURL() {
        String baseURL = URL.getSalesforceBaseUrl().toExternalForm();
        return baseURL;
    }

    public Map<String, List<Test_Run_Method_Result__c>> getFirstFailureMap() {
        if (queryResults == null) {
            queryTestRun();
        }
        Map<String, List<Test_Run_Method_Result__c>> firstFailureMap = new Map<String, List<Test_Run_Method_Result__c>>();
        for (Test_Run_Method_Result__c r : queryResults) {
            if (r.First_Failure__c.date() == Date.today()) {
                if (firstFailureMap.containsKey(r.Name)) {
                    firstFailureMap.get(r.Name).add(r);
                } else {
                    firstFailureMap.put(r.Name, new List<Test_Run_Method_Result__c>{ r });
                }
            }
        }
        return firstFailureMap;
    }
    public Map<String, List<Test_Run_Method_Result__c>> getRemainingFailureMap() {
        if (queryResults == null) {
            queryTestRun();
        }
        Map<String, List<Test_Run_Method_Result__c>> remainingFailureMap = new Map<String, List<Test_Run_Method_Result__c>>();
        for (Test_Run_Method_Result__c r : queryResults) {
            if (r.First_Failure__c.date() != Date.today()) {
                if (remainingFailureMap.containsKey(r.Name)) {
                    remainingFailureMap.get(r.Name).add(r);
                } else {
                    remainingFailureMap.put(r.Name, new List<Test_Run_Method_Result__c>{ r });
                }
            }
        }
        return remainingFailureMap;
    }

    private void queryTestRun() {
        queryResults = [
            SELECT Id, Name, Method_Name__c, Message__c, First_Failure__c
            FROM Test_Run_Method_Result__c
            WHERE Test_Run__c = :testRunId AND Method_Pass__c = false
        ];
    }
}