force-app/main/default/objects/Test_Run__c/Test_Run__c.object-meta.xml
<CustomObject>
    <label>Test Run</label>
    <nameField>
        <label>Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run__c/fields/Parent_Job_Ids__c.field-meta.xml
<CustomField>
    <fullName>Parent_Job_Ids__c</fullName>
    <externalId>true</externalId>
    <label>Parent Job Ids</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when the test run has completed and has been processed by the TestRunner package.</description>
    <inlineHelpText>True when the test run has completed and has been processed by the TestRunner package.</inlineHelpText>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/Test_Run_Method_Result__c.object-meta.xml
<CustomObject>
    <label>Test Run Method Result</label>
    <nameField>
        <label>Apex Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Run Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/First_Failure__c.field-meta.xml
<CustomField>
    <fullName>First_Failure__c</fullName>
    <description>DateTime of first failed attempt at test</description>
    <label>First Failure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Method_Pass__c.field-meta.xml
<CustomField>
    <fullName>Method_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Method Pass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/fields/Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Test_Run__c</fullName>
    <label>Test Run</label>
    <referenceTo>Test_Run__c</referenceTo>
    <relationshipLabel>Test Run Method Results</relationshipLabel>
    <relationshipName>Test_Run_Method_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

notifications/workflow-email/classes/TestRunEmailControllerTest.cls
@isTest
private class TestRunEmailControllerTest {
    @isTest
    public static void controllerTest() {
        Test_Run__c testRun = new Test_Run__c(
            Name = 'Testing Test Run',
            Parent_Job_Ids__c = '7073t00005OHeNPCA1',
            Processed__c = false
        );
        insert testRun;

        List<Test_Run_Method_Result__c> methodResults = new List<Test_Run_Method_Result__c>{
            new Test_Run_Method_Result__c(
                Name = 'Test Class',
                Method_Name__c = 'Test Method',
                Message__c = 'Testing email controller',
                Method_Pass__c = false,
                First_Failure__c = Datetime.now(),
                Test_Run__c = testRun.Id
            ),
            new Test_Run_Method_Result__c(
                Name = 'Test Class2',
                Method_Name__c = 'Test Method2',
                Message__c = 'Testing email controller',
                Method_Pass__c = false,
                First_Failure__c = Datetime.now().addDays(-1),
                Test_Run__c = testRun.Id
            )
        };
        insert methodResults;

        TestRunEmailController cont = new TestRunEmailController();
        cont.testRunId = testRun.Id;
        Map<String, List<Test_Run_Method_Result__c>> contMap = cont.getFirstFailureMap();
        System.assert(!contMap.isEmpty());
        List<String> firstKey = cont.getFirstFailureKeys();
        System.assertEquals(methodResults[0].Name, firstKey[0]);
        List<String> remainingKey = cont.getRemainingFailureKeys();
        System.assertEquals(methodResults[1].Name, remainingKey[0]);
    }
}